language: node_js

node_js:
    - "0.10"
    - "0.12"
    - "4.0"

matrix:
    fast_finish: true

    include:
        - node_js: "0.10"
        - node_js: "0.12"
        - node_js: "4.0"

    allow_failures:
        - node_js: "4.0"

sudo: false
